[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    adafruit/Adafruit SHT31 Library@^2.2.2
    bogde/HX711@^0.7.5
    vshymanskyy/TinyGSM@^0.12.0
    bblanchon/ArduinoJson@^7.2.1
    bblanchon/ArduinoHttpClient@^0.6.1

build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DUSE_SECRETS

# Environment для тестирования периферии
[env:test]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    adafruit/Adafruit SHT31 Library@^2.2.2
    bogde/HX711@^0.7.5

build_flags = 
    -DCORE_DEBUG_LEVEL=3

# Указываем что тестовый код в другом месте
src_dir = test
test_build_project_src = true
