[platformio]
default_envs = gsm

; ===== COMMON SETTINGS =====
[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; ===== GSM VERSION =====
[env:gsm]
build_src_filter = 
    +<../firmware/common/*>
    +<../firmware/gsm/*>
    -<../firmware/wifi/*>
    -<../test/*>

lib_deps = 
    adafruit/Adafruit SHT31 Library@^2.2.2
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.3
    bogde/HX711@^0.7.5
    vshymanskyy/TinyGSM@^0.12.0
    bblanchon/ArduinoJson@^7.2.1
    adafruit/RTClib@^2.1.1

build_flags = 
    -DVERSION_GSM
    -DCORE_DEBUG_LEVEL=3

; ===== WIFI VERSION =====
[env:wifi]
build_src_filter = 
    +<../firmware/common/*>
    +<../firmware/wifi/*>
    -<../firmware/gsm/*>
    -<../test/*>

lib_deps = 
    adafruit/Adafruit SHT31 Library@^2.2.2
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.3
    bogde/HX711@^0.7.5
    bblanchon/ArduinoJson@^7.2.1
    adafruit/RTClib@^2.1.1
    ESP Async WebServer@^1.2.3

build_flags = 
    -DVERSION_WIFI
    -DCORE_DEBUG_LEVEL=3

; ===== TEST ENVIRONMENT =====
[env:test]
build_src_filter = +<../test/*>

lib_deps = 
    adafruit/Adafruit SHT31 Library@^2.2.2
    bogde/HX711@^0.7.5

build_flags = -DCORE_DEBUG_LEVEL=3
